name: ggbrain
description: "Geometric Animal Puzzle is a vibrant educational game for young children."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flame: ^1.23.0
  flame_audio: ^2.10.7
  http: ^1.3.0
  provider: ^6.1.4
  flutter_svg: ^2.1.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
